version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "yarn dev"
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5000:5000"

  postgres:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=psql_user
      - POSTGRES_PASSWORD=psql_pass
      - POSTGRES_DB=users_manager
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  postgres_data:
